server:
  port: 9002
  netty:
    shutdown: graceful
    connection-timeout: 2s
    idle-timeout: 15s

spring:
  application:
    name: ponto-service
  main:
    banner-mode: off
  lifecycle:
    timeout-per-shutdown-phase: 15s
  r2dbc:
    username: user
    password: password
    url: r2dbc:postgresql://localhost:5432/pontodb_ponto
    pool:
      max-create-connection-time: 2s
      initial-size: 2
      max-size: 5
  flyway:
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    url: jdbc:postgresql://localhost:5432/pontodb_ponto
  config:
    import: "optional:configserver:"
  cloud:
    stream:
      bindings:
        pontoDispatch-out-0:
          destination: ponto-dispatched
  rabbitmq:
    bindings:
      pontoDispatch-out-0:
        producer:
          transacted: true
    host: localhost
    port: 5672
    username: user
    password: password
    connection-timeout: 5s

ponto:
  funcionario-service-uri: "http://localhost:9001/api"
  temp-limit: 5

#logging:
#  level:
#    root: DEBUG